### ISSUE TITLE
Add support for Kibana 7

### ISSUE THREAD

**Issue by algattik** [microsoft/K2Bridge#13]
K2Bridge currently only supports Kibana 6. We want to support Kibana 7 (and Elasticsearch 7).

Identified gaps:
- minor changes in _msearch, already resolved in branch `spike/kibana7`
- Kibana 7 sends data retrieval searches (Discover tab) to _search rather than _msearch by default. In K2Bridge data retrieval is only implemented at the _msearch endpoint.
  - Issue #8 would potentially solve this by implementing data retrieval in the _search endpoint.
  - A partial workaround is to enable the `courier:batchSearches` option under Kibana Advanced settings, but that results in frequent UI errors related to the "timed_out" property. The cause for this seems to be that K2Bridge only returns results for the first request in an ndjson document.
 
In addition:
- need to update the build pipeline to perform parallel test of ES 6 and ES7.  Already resolved in branch `spike/kibana7`

**Comment by eladiw** [comment]
Added support
