### ISSUE TITLE
Upgrade to Elastic newer version or latest 7.17

### ISSUE THREAD

**Issue by gar0t0** [microsoft/K2Bridge#206]
Hi,

It's possible to use the newes version of Elasticsearch "eck-elasticsearch" or use the latest version 7 (7.17.3) ?

Anyone deploy that in the latest version?

Best Regards
gar0t0

**Comment by AsafMah** [comment]
This project only supports the latest OSS version of kibana - 7.10.2.
Versions made after that are not open source, and therefore we can't interface with them

As for elastic search 7.17.x - there shouldn't be any problem, I tested it myself and I can confirm it works.

Please open an issue if you encounter a specific problem in a newer version.
