### ISSUE TITLE
Add support for the 'Visualize' tab

### ISSUE THREAD

**Issue by eladiw** [microsoft/K2Bridge#3]
**Community Note**

- Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

Currently K2Bridge only supports the 'Discover' tab but we're interesting in learning if this is a valuable feature to include in the future.

**Comment by seadeer** [comment]
Adding the "Visualize" tab would be invaluable to anyone who uses ADX as their data analytics backend, as Kibana is a very powerful visualization tool. Our team has been looking for tools to bridge this gap and give users a rich "low/no code" visualization/data exploration experience and Kibana really stands out in this regard.

**Comment by eladiw** [comment]
Added! (currently in a feature branch dev-vnext)
