### ISSUE TITLE
Error if a table or a function (view) does not contain a field mentioned in the search query 

### ISSUE THREAD

**Issue by eglukhovskaya** [microsoft/K2Bridge#37]
If you mistype or use non-existent field in the search query, you get an error:
![image](https://user-images.githubusercontent.com/32196357/78647608-809dc300-78c3-11ea-9beb-833b867819bf.png)

**Comment by eladiw** [comment]
Hi @eglukhovskaya,
Thanks for your feedback.

The way it works with Kibana and Elastic is that you will not get any result (no error and no results).
However we think it makes more sense to show the error from ADX, so the users know they made a typing mistake.

@boazsha

**Comment by spacentropy** [comment]
Hi Elad. Can we make it more user-friendly? E.g. add some text like "you've probably mistyped the fields"

**Comment by eladiw** [comment]
@boazsha  @tamirkamara

**Comment by boazsha** [comment]
It is a good point and will be added. Thanks!

**Comment by eladiw** [comment]
#133
