### ISSUE TITLE
Installation doc: namespace k2bridge

### ISSUE THREAD

**Issue by willzhan** [microsoft/K2Bridge#57]
In the installation doc (https://github.com/microsoft/K2Bridge/blob/master/docs/installation.md), both of the helm commands use the switch -n k2bridge. The doc did NOT mention that such namespace should exist. One either has to create such namespace before running the helm commands or face failure.

Two questions:

1. It does not seem to be necessary to use a specific namespace instead of the default. Is this the right understanding? 
2. Regardless whether the namespace is necessary, the installation doc changes seems to be necessary?
3. I added the namespace and proceeded, Kibana portal is up and running but failed to create index pattern with an "internal server error": 

An internal server error occurred
Error: An internal server error occurred
    at http://20.85.26.253:5601/bundles/commons.bundle.js:1:1203245
    at processQueue (http://20.85.26.253:5601/built_assets/dlls/vendors.bundle.dll.js:307:199687)
    at http://20.85.26.253:5601/built_assets/dlls/vendors.bundle.dll.js:307:200650
    at Scope.$digest (http://20.85.26.253:5601/built_assets/dlls/vendors.bundle.dll.js:307:210412)
    at Scope.$apply (http://20.85.26.253:5601/built_assets/dlls/vendors.bundle.dll.js:307:213219)
    at done (http://20.85.26.253:5601/built_assets/dlls/vendors.bundle.dll.js:307:132717)
    at completeRequest (http://20.85.26.253:5601/built_assets/dlls/vendors.bundle.dll.js:307:136329)
    at XMLHttpRequest.requestLoaded (http://20.85.26.253:5601/built_assets/dlls/vendors.bundle.dll.js:307:135225)

**Comment by willzhan** [comment]
In AKS cluster authentication, I changed from System-assigned Managed Identity to Service Principal and it works now.

I suppose using Service Principal is the right way, today? Thanks.

**Comment by tamirkamara** [comment]
@willzhan, thanks for opening the issue. 
Can you explain the thing about the managed identity? Is this related to issues with installing K2Bridge on your cluster? Any details you provide will help us understand this better.
CC: @AsafMah

**Comment by eladiw** [comment]
1. Managed identity is now supported.
2. doc updated #58 
3. Regarding the index pattern creation, please provide more info, you can look for the errors in the pod logs

Alternatively, you can set collectTelemetry=true in the helm chart, this will send telemetry to our internal AppInsights instance and we might be able to assist more
