### ISSUE TITLE
Filtering according to real numbers value is not working

### ISSUE THREAD

**Issue by eladiw** [microsoft/K2Bridge#68]
Description of the problem:
Kibana trims / rounds real values, users who would like to filter according to these values are not getting any results (or wrong results)

How to reproduce:
1. Given a kusto real field in a table
![image](https://user-images.githubusercontent.com/13205761/142194819-f501aae3-84ec-465a-b6ac-7a6b1e808f9f.png)
![image](https://user-images.githubusercontent.com/13205761/142195143-233d12db-f5ce-4374-bb11-875210409a49.png)
2. Kibana shows this value as a trimmed value / rounded:
![image](https://user-images.githubusercontent.com/13205761/142195381-55cdda6c-0d26-41c8-adcb-7b9afe487f1f.png)

3. Try to filter according to that field (In Kibana):
![image](https://user-images.githubusercontent.com/13205761/142192937-26f2d41c-4755-4d52-992f-140b0f5bf004.png)
4. The generated part of the query is : 'and (CounterValue == 13.77)'
5. Results are not showing because this is not correct

**Comment by AsafMah** [comment]
I think we saw that it's a bug related to the kibana UI, and there's not much we can do about it in our service, so I'm closing for now.
